# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Push a new release build to the App Store"
lane :ios_release do
  increment_build_number(xcodeproj: "edu-app.xcodeproj")
  build_app(workspace: "edu-app.xcworkspace", scheme: "edu-app")

  app_store_connect_api_key(
    key_id: ENV["APP_STORE_KEY_ID"],
    issuer_id: ENV["APP_STORE_KEY_ISSUER_ID"],
    key_content: ENV["APP_STORE_KEY"],
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

  upload_to_app_store(
    skip_metadata: true,
    skip_screenshots: true,
    precheck_include_in_app_purchases: false
  )
end

desc "Run tests"
lane :test do
  run_tests(workspace: "edu-app.xcworkspace",
            devices: ["iPhone 15"],
            run_rosetta_simulator: true,
            output_types: "junit",
            fail_build: false,
            result_bundle: true)

  trainer(path: "./fastlane/test_output", output_directory: "./fastlane")
end