name: Run tests

on: workflow_call

jobs:
  test:
    name: Run tests for the app
    runs-on: self-hosted
    steps:
        - name: Install pods
          run: pod install
        - name: Set permission for executing test script
          run: chmod +x ./.github/scripts/test.sh
        - name: Run tests
          id: run_tests
          run: ./.github/scripts/test.sh