name: Publish app nativley

on:
  workflow_dispatch:
    inputs:
      deployDestination:
        type: choice
        description: Where do you want to upload the app
        options:
        - appStore
        - testFlight

jobs:
  deploy:
    name: Deploying to App Store
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pods
        run: pod install
      - name: Set permissions for decrypt script
        run: chmod +x ./.github/secrets/decrypt_secrets.sh
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Set permissions for archive script
        run: chmod +x ./.github/scripts/archive_app.sh
      - name: Archiving project
        run: ./.github/scripts/archive_app.sh
      - name: Set permissions for export script
        run: chmod +x ./.github/scripts/export_ipa_${{ inputs.deployDestination }}.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa_${{ inputs.deployDestination }}.sh
      - name: Set permissions for publishing script
        run: chmod +x ./.github/scripts/upload_app.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        #run: ./.github/scripts/upload_app.sh
        run: echo "Should upload to store"
