name: Publish app to App Store nativley

# TODO: There is a release event which can be used
on:
  workflow_dispatch:

# TODO: Try doing it with https://github.com/marketplace/actions/ios-build-action

jobs:
  deploy:
    name: Deploying to App Store
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install gpg
        run: brew install gnupg
      - name: Check GPG version
        run: gpg --version
      - name: Remove pods # Debugging
        run: pod deintegrate
      - name: Install pods # Debugging
        run: pod install
      - name: Set permissions for decrypt script
        run: chmod +x ./.github/secrets/decrypt_secrets.sh
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Set permissions for archive script
        run: chmod +x ./.github/scripts/archive_app.sh
      - name: Archiving project
        run: ./.github/scripts/archive_app.sh
      - name: Set permissions for export script
        run: chmod +x ./.github/scripts/export_ipa_appStore.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa_appStore.sh
      - name: Set permissions for publishing script
        run: chmod +x ./.github/scripts/upload_app.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        #run: ./.github/scripts/upload_app.sh
        run: echo "Should upload to store"
