name: Run tests for Pull Request using fastlane

on: pull_request

jobs:
  test:
    runs-on: self-hosted
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Run tests
          uses: ./.github/actions/test_fastlane
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action/composite@v2
          if: success() || failure()
          with:
            files: |
              build/reports/junit.xml