name: Run tests nightly

on: workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    name: Run nightly tests for the app
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Run reusable test workflow
          uses: ./.github/actions/test