name: Run tests

on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: macos-latest
    steps:
        - name: Comment PR
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: "Hello !!!"