name: Run tests

on:
  pull_request:
    types: labeled

jobs:
  test:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: self-hosted
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Install pods
          run: pod install
        - name: Set permission for executing test script
          run: chmod +x ./.github/scripts/test.sh
        - name: Run tests
          id: run_tests
          run: ./.github/scripts/test.sh
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
              files: |
                build/reports/junit.xml
        #- name: Comment PR
        #  uses: thollander/actions-comment-pull-request@v2
        #  with:
        #    message: ${{join(steps.run_tests.outputs.*, '\n')}}